name: Update feed snippet

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install feedsnippet
        run: go install github.com/anton-fuji/feedsnippet@latest

      - name: Update README.md
        run: feedsnippet -config config.yml -diff -file README.md

      - name: git commit
        run: |
          git config --local user.email "anton-fuji@users.noreply.github.com"
          git config --local user.name "anton-fuji"
          git add README.md
          git diff --cached --quiet || (git commit -m "Update feed snippet" && git push origin main)